// 0fc332de9b5d81933b026d524d614bc11577d39a
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "1.3.3-365-g0fc332d-m"
#define GIT_HASH "0fc332de9b5d81933b026d524d614bc11577d39a"
#define GIT_TIME "2020-09-05 19:21:02 -0400"
#define GIT_DATE_INT 1599348062ull
